"""Initial3

Revision ID: 83752fa42672
Revises: dd9fbbe90193
Create Date: 2024-05-25 21:21:26.538096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83752fa42672'
down_revision = 'dd9fbbe90193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_test_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['test_id'], ondelete='CASCADE')
    op.drop_constraint('scores_test_id_fkey', 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'tests', ['test_id'], ['test_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key('scores_test_id_fkey', 'scores', 'tests', ['test_id'], ['test_id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_test_id_fkey', 'questions', 'tests', ['test_id'], ['test_id'])
    # ### end Alembic commands ###
