"""Initial2

Revision ID: dd9fbbe90193
Revises: 3871925c435e
Create Date: 2024-05-25 21:11:39.423764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9fbbe90193'
down_revision = '3871925c435e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
