version: "3.0"

services:
  database:
    container_name: "database"
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata_app:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis:6.2-alpine
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=password
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  backend-app:
    container_name: "backend-app"
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../src:/home/my_user/src
    ports:
      - '8000:8000'
    depends_on:
      - database
    env_file:
      - ../../../../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  pgdata_app:
  cache: